/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for HTML to Markdown conversion. */
export interface ConvertOptions {
  /** Heading style: "atx" (default) or "setext" */
  headingStyle?: string
  /** Link style: "inline" (default) or "referenced" */
  linkStyle?: string
  /** Code fence character: "`" (default) or "~" */
  codeFence?: string
  /** Bullet marker for unordered lists: "-" (default), "*", or "+" */
  bulletMarker?: string
  /** Base URL for resolving relative links */
  baseUrl?: string
  /** CSS selectors for elements to exclude */
  excludeSelectors?: Array<string>
  /** CSS selectors for elements to force keep (overrides excludes) */
  includeSelectors?: Array<string>
}
/**
 * Convert HTML to Markdown synchronously.
 *
 * @param html - The HTML string to convert
 * @param options - Optional conversion options
 * @returns The converted Markdown string
 */
export declare function convert(html: string, options?: ConvertOptions | undefined | null): string
/**
 * Convert HTML to Markdown asynchronously.
 *
 * This is useful for large documents to avoid blocking the main thread.
 *
 * @param html - The HTML string to convert
 * @param options - Optional conversion options
 * @returns A promise that resolves to the converted Markdown string
 */
export declare function convertAsync(html: string, options?: ConvertOptions | undefined | null): Promise<string>
